-- ============================================================================
-- RLS Policies — Allow authenticated users to read/write all tables
-- MVP mode: permissive. Tighten in production.
-- ============================================================================

alter table if exists admin_roles enable row level security;
alter table if exists admin_users enable row level security;
alter table if exists admin_permissions enable row level security;
alter table if exists admin_audit_logs enable row level security;
alter table if exists profiles enable row level security;
alter table if exists plans enable row level security;
alter table if exists subscriptions enable row level security;
alter table if exists user_credits enable row level security;
alter table if exists credit_transactions enable row level security;
alter table if exists ai_models enable row level security;
alter table if exists ai_provider_configs enable row level security;
alter table if exists prompt_templates enable row level security;
alter table if exists ai_jobs enable row level security;
alter table if exists ai_generation_logs enable row level security;
alter table if exists product_categories enable row level security;
alter table if exists product_tags enable row level security;
alter table if exists product_sources enable row level security;
alter table if exists products enable row level security;
alter table if exists product_sync_logs enable row level security;
alter table if exists product_clicks enable row level security;
alter table if exists fashion_trends enable row level security;
alter table if exists trend_keywords enable row level security;
alter table if exists trend_colors enable row level security;
alter table if exists style_presets enable row level security;
alter table if exists trend_products enable row level security;
alter table if exists payments enable row level security;
alter table if exists billing_events enable row level security;
alter table if exists invoices enable row level security;
alter table if exists analytics_events enable row level security;
alter table if exists daily_user_metrics enable row level security;
alter table if exists daily_ai_metrics enable row level security;
alter table if exists daily_affiliate_metrics enable row level security;
alter table if exists daily_revenue_metrics enable row level security;
alter table if exists device_tokens enable row level security;
alter table if exists notifications enable row level security;
alter table if exists notification_logs enable row level security;
alter table if exists user_reports enable row level security;
alter table if exists report_actions enable row level security;
alter table if exists blocked_keywords enable row level security;
alter table if exists moderation_logs enable row level security;
alter table if exists content_safety_rules enable row level security;
alter table if exists system_settings enable row level security;
alter table if exists feature_flags enable row level security;
alter table if exists rate_limits enable row level security;
alter table if exists wardrobe_items enable row level security;
alter table if exists outfits enable row level security;
alter table if exists outfit_items enable row level security;
alter table if exists user_activity_log enable row level security;

create policy if not exists "rls_authenticated_all_admin_roles" on admin_roles for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_admin_users" on admin_users for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_admin_permissions" on admin_permissions for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_admin_audit_logs" on admin_audit_logs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_profiles" on profiles for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_plans" on plans for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_subscriptions" on subscriptions for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_user_credits" on user_credits for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_credit_transactions" on credit_transactions for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_ai_models" on ai_models for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_ai_provider_configs" on ai_provider_configs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_prompt_templates" on prompt_templates for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_ai_jobs" on ai_jobs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_ai_generation_logs" on ai_generation_logs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_product_categories" on product_categories for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_product_tags" on product_tags for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_product_sources" on product_sources for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_products" on products for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_product_sync_logs" on product_sync_logs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_product_clicks" on product_clicks for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_fashion_trends" on fashion_trends for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_trend_keywords" on trend_keywords for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_trend_colors" on trend_colors for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_style_presets" on style_presets for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_trend_products" on trend_products for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_payments" on payments for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_billing_events" on billing_events for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_invoices" on invoices for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_analytics_events" on analytics_events for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_daily_user_metrics" on daily_user_metrics for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_daily_ai_metrics" on daily_ai_metrics for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_daily_affiliate_metrics" on daily_affiliate_metrics for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_daily_revenue_metrics" on daily_revenue_metrics for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_device_tokens" on device_tokens for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_notifications" on notifications for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_notification_logs" on notification_logs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_user_reports" on user_reports for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_report_actions" on report_actions for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_blocked_keywords" on blocked_keywords for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_moderation_logs" on moderation_logs for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_content_safety_rules" on content_safety_rules for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_system_settings" on system_settings for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_feature_flags" on feature_flags for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_rate_limits" on rate_limits for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_wardrobe_items" on wardrobe_items for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_outfits" on outfits for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_outfit_items" on outfit_items for all to authenticated using (true) with check (true);
create policy if not exists "rls_authenticated_all_user_activity_log" on user_activity_log for all to authenticated using (true) with check (true);
